const fs = require('fs');
const getVpnList = require("./lib/main");

const saveBase64ToFile = (base64Data, filename) => {
    const buffer = Buffer.from(base64Data, 'base64');
    fs.writeFileSync(filename, buffer);
};

const generateReadme = (servers) => {
    let content = `# VPN List\n\n`;
    content += `This is an auto-generated list of VPNs retrieved from a specific source.\n\n`;
    
    content += `## Last Updated\n\n`;
    content += `This list was last updated on: ${getDate(Date.now())}.\n\n`;
    
    content += `## Available Servers\n\n`;
    content += `Below is the list of available VPN servers (US and CA only, max 20):\n\n`;

    content += "| Hostname | IP Address | Ping | Speed | Country | Update Time | OpenVPN Config |\n";
    content += "|----------|------------|-------|-------|---------|-------------|----------------|\n";
    servers.forEach((server, index) => {
        let speedInMbps = (server.speed / 10000000).toFixed(2); // Convert to Mbps and round to two decimal places
        let updateTime = getDate(server.updatedAt || Date.now());
        content += `| ${server.hostname} | ${server.ip} | ${server.ping} | ${speedInMbps} Mbps | ${server.countrylong} | ${updateTime} | [Download 📥](./configs/${server.countryshort}_${String(index).padStart(2, '0')}_${server.ip}.ovpn) |\n`;
    });

    content += `\n\n### Note: Please respect the terms of use for each VPN.\n\n`;

    content += `---\n\n`;
    content += `Generated by [fdciabdul](#) | [imtaqin.id](imtaqin.id)\n\n`;

    fs.writeFileSync('README.md', content);
}

const getDate = (unix) => {
    return `${new Date(unix).toISOString().replace(/T/, ' ').replace(/\..+/, '')} UTC`;
}

// Ensure clean configs directory
if (fs.existsSync('./configs')) {
    fs.rmSync('./configs', { recursive: true, force: true });
}
fs.mkdirSync('./configs');

// Ensure json directory exists
if (!fs.existsSync('./json')) {
    fs.mkdirSync('./json');
}

const SERVERS_JSON_PATH = "json/20_servers.json";

getVpnList()
    .then(vpnList => {
        // Filter API list for US and CA
        let apiServers = vpnList.servers.filter(s => s.countryshort === 'US' || s.countryshort === 'CA');
        
        // Read existing servers
        let existingServers = [];
        if (fs.existsSync(SERVERS_JSON_PATH)) {
            try {
                existingServers = JSON.parse(fs.readFileSync(SERVERS_JSON_PATH, 'utf-8'));
            } catch(e) {
                console.error("Error reading existing servers json:", e);
                existingServers = [];
            }
        }

        // Identify new servers from API
        let existingIps = new Set(existingServers.map(s => s.ip));
        let newServers = apiServers.filter(s => !existingIps.has(s.ip));

        // Update the 20 slots
        // Sort existing by updatedAt ascending (oldest first)
        existingServers.sort((a, b) => (a.updatedAt || 0) - (b.updatedAt || 0));

        for (let newS of newServers) {
            newS.updatedAt = Date.now();
            if (existingServers.length < 20) {
                existingServers.push(newS);
            } else {
                // Replace the oldest one
                existingServers[0] = newS;
                // Re-sort so the new oldest is at index 0
                existingServers.sort((a, b) => (a.updatedAt || 0) - (b.updatedAt || 0));
            }
        }

        // Now sort for display: CA first, then US. 
        // For servers of the same country, we sort by speed descending.
        existingServers.sort((a, b) => {
            if (a.countryshort === 'CA' && b.countryshort !== 'CA') return -1;
            if (a.countryshort !== 'CA' && b.countryshort === 'CA') return 1;
            return b.speed - a.speed;
        });

        // Ensure we strictly have at most 20 servers
        existingServers = existingServers.slice(0, 20);

        // Save state
        fs.writeFileSync(SERVERS_JSON_PATH, JSON.stringify(existingServers, null, 4), "utf-8");

        // Generate configs
        existingServers.forEach((server, index) => {
            const configData = server.openvpn_configdata_base64;
            saveBase64ToFile(configData, `./configs/${server.countryshort}_${String(index).padStart(2, '0')}_${server.ip}.ovpn`);
        });

        // Generate README
        generateReadme(existingServers);
    })
    .catch(err => {
        console.log(err);
    });
