const fs = require('fs');
const ping = require('ping');
const getVpnList = require("./lib/main");

const saveBase64ToFile = (base64Data, filename) => {
    const buffer = Buffer.from(base64Data, 'base64');
    fs.writeFileSync(filename, buffer);
};

const generateReadme = (servers) => {
    let content = `# OpenVPN List\n\n`;
    content += `This is an auto-generated list of VPNs retrieved from a specific source.\n\n`;


    content += "| Config | CC | Speed | Hostname | IP&nbsp;Address | Ping | update |\n";
    content += "|-------------|----|-------|----------|------------|-------|--------|\n";
    servers.forEach((server, index) => {
        let speedInMbps = (server.speed / 10000000).toFixed(2); // Convert to Mbps and round to two decimal places
        let updateTime = getDate(server.updatedAt || Date.now());
        let fileName = `${server.countryshort}_${String(index).padStart(2, '0')}_${server.ip}.ovpn`;
        let downloadLinks = `[Download](./configs/${fileName})`;
        let hostname = server.hostname ? server.hostname.replace(/ /g, '&nbsp;').replace(/-/g, '&#8209;') : '';
        let updateNoWrap = updateTime.replace(/ /g, '&nbsp;').replace(/-/g, '&#8209;');
        content += `| ${downloadLinks} | ${server.countryshort} | ${speedInMbps}&nbsp;Mbps | ${hostname} | ${server.ip} | ${server.ping} | ${updateNoWrap} |\n`;
    });

    content += `\n\n### Note: Please respect the terms of use for each VPN.\n\n`;

    content += `---\n\n`;
    content += `Generated by [kanpianer](https://github.com/kanpianer/Vpngate-Scraper-API-US.CA.JP) | [fdciabdul](https://github.com/fdciabdul/Vpngate-Scraper-API) \n [imtaqin.id](https://imtaqin.id/)\n\n`;
    fs.writeFileSync('README.md', content);
}

const getDate = (unix) => {
    // Convert to Beijing Time (UTC+8)
    const beijingTime = new Date(unix + 8 * 60 * 60 * 1000).toISOString();
    return `${beijingTime.substring(5, 10)} ${beijingTime.substring(11, 16)} CST`;
}

// Ensure clean configs directory
if (fs.existsSync('./configs')) {
    fs.rmSync('./configs', { recursive: true, force: true });
}
fs.mkdirSync('./configs');

// Ensure json directory exists
if (!fs.existsSync('./json')) {
    fs.mkdirSync('./json');
}

const SERVERS_JSON_PATH = "json/30_servers.json";

    if (!process.env.GITHUB_ACTIONS) {
        console.log("Local environment detected, skipping data update to prevent conflicts.");
        process.exit(0);
    }

    getVpnList()
    .then(vpnList => {
        // Filter API list for JP, US, and CA, and speed >= 8 Mbps (speed >= 80000000)
        let apiServers = vpnList.servers.filter(s => (s.countryshort === 'JP' || s.countryshort === 'US' || s.countryshort === 'CA') && s.speed >= 80000000);
        
        // Read existing servers
        let existingServers = [];
        if (fs.existsSync(SERVERS_JSON_PATH)) {
            try {
                existingServers = JSON.parse(fs.readFileSync(SERVERS_JSON_PATH, 'utf-8'));
                existingServers = existingServers.filter(s => s.speed >= 80000000); // Exclude < 8 Mbps
            } catch(e) {
                console.error("Error reading existing servers json:", e);
                existingServers = [];
            }
        }

        // Identify new servers from API
        let existingIps = new Set(existingServers.map(s => s.ip));
        let newServersRaw = apiServers.filter(s => !existingIps.has(s.ip));

        console.log(`Pinging ${newServersRaw.length} new servers...`);
        
        return Promise.all(newServersRaw.map(s => ping.promise.probe(s.ip, { timeout: 2 })))
            .then(pingResults => {
                let newServers = newServersRaw.filter((s, index) => pingResults[index].alive);
                console.log(`Ping complete. ${newServers.length} out of ${newServersRaw.length} new servers are alive.`);
                
                // Update the 30 slots (10 for JP, 20 for US/CA)
                let existingJP = existingServers.filter(s => s.countryshort === 'JP');
                let existingOther = existingServers.filter(s => s.countryshort !== 'JP');
                let newJP = newServers.filter(s => s.countryshort === 'JP');
                let newOther = newServers.filter(s => s.countryshort !== 'JP');

        const updateList = (existingList, newList, maxCount) => {
            existingList.sort((a, b) => (a.updatedAt || 0) - (b.updatedAt || 0));
            for (let newS of newList) {
                newS.updatedAt = Date.now();
                if (existingList.length < maxCount) {
                    existingList.push(newS);
                } else {
                    existingList[0] = newS;
                    existingList.sort((a, b) => (a.updatedAt || 0) - (b.updatedAt || 0));
                }
            }
            return existingList;
        }

        existingJP = updateList(existingJP, newJP, 10);
        existingOther = updateList(existingOther, newOther, 20);
        
        existingServers = [...existingJP, ...existingOther];

        // Now sort for display: US first, then CA, then JP. 
        // For servers of the same country, we sort by speed descending.
        existingServers.sort((a, b) => {
            const order = { 'US': 1, 'CA': 2, 'JP': 3 };
            const orderA = order[a.countryshort] || 99;
            const orderB = order[b.countryshort] || 99;
            if (orderA !== orderB) {
                return orderA - orderB;
            }
            return b.speed - a.speed;
        });

        // Ensure we strictly have at most 30 servers
        existingServers = existingServers.slice(0, 30);

        // Save state
        fs.writeFileSync(SERVERS_JSON_PATH, JSON.stringify(existingServers, null, 4), "utf-8");

        // Generate configs
        existingServers.forEach((server, index) => {
            const configData = server.openvpn_configdata_base64;
            saveBase64ToFile(configData, `./configs/${server.countryshort}_${String(index).padStart(2, '0')}_${server.ip}.ovpn`);
        });

        // Generate README
        generateReadme(existingServers);
            });
    })
    .catch(err => {
        console.log(err);
    });
